title: Bhavnesh Jangid
theme: minima
description: Personal website of Bhavnesh Jangid
url: "https://jangidbhavnesh.github.io"
markdown: kramdown
header_pages:
  - about.md
  - publications.md
  - research-projects.md
  - code-contributions.md
  - blog.md