title: Bhavnesh Jangid
theme: minima
description: Personal website of Bhavnesh Jangid
url: "https://jangidbhavnesh.github.io"
markdown: kramdown
header_pages:
  - About/index.md
  - Publications/index.md
  - Projects/index.md
  - Code/index.md
  - Blog/index.md